apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
  namespace: laravel-app
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "https://laravel.example.com"
  DB_CONNECTION: "pgsql"
  # DB_HOST: "postgres-service"
  DB_HOST: "10.40.120.216"
  DB_PORT: "5432"
  DB_DATABASE: "laravel"