apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
  namespace: laravel-app
type: Opaque
stringData:
  APP_KEY: "base64:PVuuDwI0Ah3OZ0+lNK8sj0O3REk6sgiWkfNeLGIs+IE="  # Ganti dengan key dari php artisan key:generate --show
  DB_USERNAME: "lara_db_user"
  DB_PASSWORD: "lara_123!!"
  #POSTGRES_PASSWORD: "your_strong_password"
  #POSTGRES_USER: "laravel"